// Prepared short phrases for non-AI move types (all <= 60 chars)
// AI only explains: Blunder, Mistake, Brilliant

export const preparedTexts: Record<string, string[]> = {
  Best: [
    "That's the right idea.",
    "Best move!",
    "Nice eye.",
    "Couldn't be better.",
    "Spot on!",
    "Perfect choice.",
    "Engine approved.",
    "Exactly right.",
    "Top move.",
    "Nailed it.",
    "Sharp play.",
    "Precision.",
    "Textbook.",
    "Flawless.",
    "Crushed it.",
  ],
  Great: [
    "Strong follow-up.",
    "Keeps the squeeze.",
    "Clean play.",
    "Great instincts.",
    "Power move.",
    "Impressive.",
    "Well spotted.",
    "Showing class.",
    "That hurts them.",
    "Dangerous.",
    "Putting pressure on.",
    "Nice technique.",
  ],
  Excellent: [
    "Nearly perfect.",
    "Top-tier choice.",
    "Engine-level find.",
    "Very strong.",
    "Excellent judgment.",
    "High-quality move.",
    "Almost the best.",
    "Impressive accuracy.",
    "Super solid.",
    "Really well played.",
  ],
  Good: [
    "Solid choice.",
    "Keeps things stable.",
    "Safe, steady move.",
    "Reasonable.",
    "Gets the job done.",
    "No complaints.",
    "Practical.",
    "Sensible.",
    "Stays on track.",
    "Fair enough.",
    "Keeps balance.",
  ],
  Inaccuracy: [
    "Small slip; still okay.",
    "Slightly drifts.",
    "Not critical.",
    "Minor wobble.",
    "Could be sharper.",
    "Lets tension slip.",
    "Missed a nuance.",
    "A bit passive.",
    "Room for improvement.",
    "Not the tightest.",
    "Slight misstep.",
  ],
  Book: [
    "Theory move.",
    "Staying in book.",
    "Standard line.",
    "Known territory.",
    "Opening prep.",
    "By the book.",
    "Mainline theory.",
    "Well-trodden path.",
    "Classical approach.",
  ],
  Miss: [
    "Missed the punishing line.",
    "Chance slipped away.",
    "Let them off the hook.",
    "Opportunity missed.",
    "Could've pounced.",
    "They got lucky.",
    "Didn't capitalize.",
    "The knockout was there.",
    "Hesitation cost you.",
  ],
  // Fallback texts for AI-explained moves (shown if AI is disabled or fails)
  Blunder: [
    "A serious error that changes the game.",
    "This move loses significant material or position.",
    "Critical mistake - check the best move above.",
    "Big oversight here.",
    "This hands the advantage to the opponent.",
  ],
  Mistake: [
    "This move weakens your position.",
    "Not the best choice here.",
    "There was a better option available.",
    "This gives up some advantage.",
    "A slip that costs you.",
  ],
  Brilliant: [
    "Exceptional move!",
    "A stroke of genius.",
    "Outstanding tactical vision.",
    "Incredible find!",
    "World-class move.",
  ],
  Unknown: [
    "Move played.",
    "No data available.",
    "Unclassified move.",
    "Analysis pending.",
  ],
};

// AI-explainable move types
export const AI_EXPLAINABLE_TYPES = ["Blunder", "Mistake", "Brilliant"];
