import Bot from "../models/Bot.js";

const botSeedData = [

  {
    name: "Nelson",
    avatar: "🧒",
    avatarUrl: "/images/Test.png",
    eloRating: 250,
    difficulty: "beginner",
    category: "Learning Bots",
    description:
      "Just learning the rules! Makes lots of mistakes and hangs pieces frequently.",
    personality: "Oops, I hung my queen again!",
    playStyle: "random",
    skillLevel: 0,
    depth: 1,
    thinkTimeMs: 500,
    blunderChance: 0.45,
    aggressiveness: 0,
    openingBook: false,
    isActive: true,
    sortOrder: 1,
  },
  {
    name: "Lily",
    avatar: "🌸",
    avatarUrl: "/images/Test.png",
    eloRating: 300,
    difficulty: "beginner",
    category: "Learning Bots",
    description:
      "A sweet beginner who's still figuring out how the pieces move.",
    personality: "Still learning the rules!",
    playStyle: "random",
    skillLevel: 0,
    depth: 1,
    thinkTimeMs: 600,
    blunderChance: 0.4,
    aggressiveness: -10,
    openingBook: false,
    isActive: true,
    sortOrder: 2,
  },
  {
    name: "Bobby",
    avatar: "⚽",
    avatarUrl: "/images/Test.png",
    eloRating: 400,
    difficulty: "beginner",
    category: "Learning Bots",
    description:
      "A sporty kid who treats chess like a fun game. Energetic but imprecise.",
    personality: "Chess is fun!",
    playStyle: "aggressive",
    skillLevel: 1,
    depth: 2,
    thinkTimeMs: 700,
    blunderChance: 0.35,
    aggressiveness: 30,
    openingBook: false,
    isActive: true,
    sortOrder: 3,
  },
  {
    name: "Emma",
    avatar: "📚",
    avatarUrl: "/images/Test.png",
    eloRating: 500,
    difficulty: "beginner",
    category: "Learning Bots",
    description:
      "A studious player who's improving rapidly. Starting to see basic tactics.",
    personality: "Getting better every game!",
    playStyle: "balanced",
    skillLevel: 1,
    depth: 2,
    thinkTimeMs: 800,
    blunderChance: 0.3,
    aggressiveness: 5,
    openingBook: false,
    isActive: true,
    sortOrder: 4,
  },

  {
    name: "Alex",
    avatar: "🎮",
    avatarUrl: "/images/Test.png",
    eloRating: 700,
    difficulty: "casual",
    category: "Casual Players",
    description:
      "A gamer who picked up chess recently. Quick moves, casual attitude.",
    personality: "Just here for a good time!",
    playStyle: "aggressive",
    skillLevel: 2,
    depth: 3,
    thinkTimeMs: 1000,
    blunderChance: 0.25,
    aggressiveness: 20,
    openingBook: false,
    isActive: true,
    sortOrder: 5,
  },
  {
    name: "Mia",
    avatar: "☕",
    avatarUrl: "/images/Test.png",
    eloRating: 800,
    difficulty: "casual",
    category: "Casual Players",
    description:
      "Enjoys a relaxed game with her morning coffee. No rush, no stress.",
    personality: "Chess and chill",
    playStyle: "defensive",
    skillLevel: 3,
    depth: 4,
    thinkTimeMs: 1500,
    blunderChance: 0.2,
    aggressiveness: -20,
    openingBook: true,
    isActive: true,
    sortOrder: 6,
  },
  {
    name: "Jordan",
    avatar: "🏀",
    avatarUrl: "/images/Test.png",
    eloRating: 900,
    difficulty: "casual",
    category: "Casual Players",
    description:
      "Athlete mindset - plays for fun but hates losing. Solid fundamentals.",
    personality: "Playing for fun",
    playStyle: "balanced",
    skillLevel: 4,
    depth: 5,
    thinkTimeMs: 1500,
    blunderChance: 0.18,
    aggressiveness: 10,
    openingBook: true,
    isActive: true,
    sortOrder: 7,
  },
  {
    name: "Sam",
    avatar: "🎯",
    avatarUrl: "/images/Test.png",
    eloRating: 1000,
    difficulty: "casual",
    category: "Casual Players",
    description:
      "The bridge between casual and competitive. Can surprise you with tactics.",
    personality: "Relaxed but competitive",
    playStyle: "balanced",
    skillLevel: 5,
    depth: 6,
    thinkTimeMs: 2000,
    blunderChance: 0.15,
    aggressiveness: 15,
    openingBook: true,
    isActive: true,
    sortOrder: 8,
  },

  {
    name: "Viktor",
    avatar: "⚔️",
    avatarUrl: "/images/Test.png",
    eloRating: 1200,
    difficulty: "intermediate",
    category: "Club Players",
    description:
      "A tactical wizard who loves combinations. Member of local chess club.",
    personality: "Tactics win games!",
    playStyle: "aggressive",
    skillLevel: 7,
    depth: 8,
    thinkTimeMs: 2500,
    blunderChance: 0.1,
    aggressiveness: 40,
    openingBook: true,
    isActive: true,
    sortOrder: 9,
  },
  {
    name: "Sofia",
    avatar: "👸",
    avatarUrl: "/images/Test.png",
    eloRating: 1300,
    difficulty: "intermediate",
    category: "Club Players",
    description:
      "Classical player who values pawn structure and central control.",
    personality: "Control the center",
    playStyle: "balanced",
    skillLevel: 8,
    depth: 9,
    thinkTimeMs: 2500,
    blunderChance: 0.08,
    aggressiveness: 0,
    openingBook: true,
    isActive: true,
    sortOrder: 10,
  },
  {
    name: "Chen",
    avatar: "🧘",
    avatarUrl: "/images/Test.png",
    eloRating: 1400,
    difficulty: "intermediate",
    category: "Club Players",
    description:
      "A patient strategist who builds advantages slowly but surely.",
    personality: "Patience is key",
    playStyle: "defensive",
    skillLevel: 9,
    depth: 10,
    thinkTimeMs: 3000,
    blunderChance: 0.06,
    aggressiveness: -25,
    openingBook: true,
    isActive: true,
    sortOrder: 11,
  },
  {
    name: "Aria",
    avatar: "🎭",
    avatarUrl: "/images/Test.png",
    eloRating: 1500,
    difficulty: "intermediate",
    category: "Club Players",
    description:
      "Thoughtful player who considers multiple plans before committing.",
    personality: "Think before you move",
    playStyle: "balanced",
    skillLevel: 10,
    depth: 11,
    thinkTimeMs: 3000,
    blunderChance: 0.05,
    aggressiveness: 5,
    openingBook: true,
    isActive: true,
    sortOrder: 12,
  },

  {
    name: "Dmitri",
    avatar: "🎩",
    avatarUrl: "/images/Test.png",
    eloRating: 1700,
    difficulty: "advanced",
    category: "Advanced Players",
    title: "CM",
    description: "Candidate Master with sharp positional understanding.",
    personality: "Every move counts",
    playStyle: "balanced",
    skillLevel: 12,
    depth: 13,
    thinkTimeMs: 3000,
    blunderChance: 0.03,
    aggressiveness: 10,
    openingBook: true,
    isActive: true,
    sortOrder: 13,
  },
  {
    name: "Nadia",
    avatar: "💎",
    avatarUrl: "/images/Test.png",
    eloRating: 1800,
    difficulty: "advanced",
    category: "Advanced Players",
    title: "WFM",
    description:
      "Woman FIDE Master known for precise calculation and powerful attacks.",
    personality: "Precision and power",
    playStyle: "aggressive",
    skillLevel: 13,
    depth: 14,
    thinkTimeMs: 3000,
    blunderChance: 0.025,
    aggressiveness: 35,
    openingBook: true,
    isActive: true,
    sortOrder: 14,
  },
  {
    name: "Marco",
    avatar: "🏛️",
    avatarUrl: "/images/Test.png",
    eloRating: 1900,
    difficulty: "advanced",
    category: "Advanced Players",
    title: "FM",
    description: "FIDE Master who values deep strategy over quick tactics.",
    personality: "Strategy over speed",
    playStyle: "defensive",
    skillLevel: 14,
    depth: 15,
    thinkTimeMs: 3000,
    blunderChance: 0.02,
    aggressiveness: -15,
    openingBook: true,
    isActive: true,
    sortOrder: 15,
  },
  {
    name: "Zara",
    avatar: "🔮",
    avatarUrl: "/images/Test.png",
    eloRating: 2000,
    difficulty: "advanced",
    category: "Advanced Players",
    title: "FM",
    description:
      "FIDE Master with exceptional calculation abilities. Very challenging.",
    personality: "Deep calculation required",
    playStyle: "balanced",
    skillLevel: 15,
    depth: 16,
    thinkTimeMs: 3000,
    blunderChance: 0.015,
    aggressiveness: 20,
    openingBook: true,
    isActive: true,
    sortOrder: 16,
  },

  {
    name: "Grandmaster Boris",
    avatar: "🧔‍♂️",
    avatarUrl: "/images/Test.png",
    eloRating: 2200,
    difficulty: "master",
    category: "Masters",
    title: "IM",
    description: "International Master with decades of tournament experience.",
    personality: "I see all possibilities",
    playStyle: "balanced",
    skillLevel: 16,
    depth: 18,
    thinkTimeMs: 3000,
    blunderChance: 0.01,
    aggressiveness: 10,
    openingBook: true,
    isActive: true,
    sortOrder: 17,
  },
  {
    name: "Alexandra",
    avatar: "👑",
    avatarUrl: "/images/Test.png",
    eloRating: 2400,
    difficulty: "master",
    category: "Masters",
    title: "IM",
    description: "International Master who views chess as artistic expression.",
    personality: "Chess is art",
    playStyle: "balanced",
    skillLevel: 17,
    depth: 20,
    thinkTimeMs: 3000,
    blunderChance: 0.008,
    aggressiveness: 5,
    openingBook: true,
    isActive: true,
    sortOrder: 18,
  },
  {
    name: "Magnus",
    avatar: "🦁",
    avatarUrl: "/images/Test.png",
    eloRating: 2600,
    difficulty: "master",
    category: "Masters",
    title: "GM",
    description:
      "Grandmaster with universal playing style. Adapts to any position.",
    personality: "Universal playing style",
    playStyle: "balanced",
    skillLevel: 19,
    depth: 22,
    thinkTimeMs: 3000,
    blunderChance: 0.005,
    aggressiveness: 15,
    openingBook: true,
    isActive: true,
    sortOrder: 19,
  },
  {
    name: "Hikaru",
    avatar: "⚡",
    avatarUrl: "/images/Test.png",
    eloRating: 2800,
    difficulty: "master",
    category: "Masters",
    title: "GM",
    description: "Super Grandmaster level. Lightning fast and deadly accurate.",
    personality: "Speed and accuracy combined",
    playStyle: "aggressive",
    skillLevel: 20,
    depth: 25,
    thinkTimeMs: 3000,
    blunderChance: 0,
    aggressiveness: 25,
    openingBook: true,
    isActive: true,
    sortOrder: 20,
  },

  {
    name: "Snowboarder",
    avatar: "🏂",
    avatarUrl: "/images/Test.png",
    eloRating: 1000,
    difficulty: "casual",
    category: "Winter Athletes",
    description:
      "Cool and stylish player who loves flashy moves and combinations.",
    personality: "Tricks and tactics!",
    playStyle: "aggressive",
    skillLevel: 5,
    depth: 6,
    thinkTimeMs: 1500,
    blunderChance: 0.15,
    aggressiveness: 45,
    openingBook: true,
    isActive: true,
    sortOrder: 21,
  },
  {
    name: "Skier",
    avatar: "⛷️",
    avatarUrl: "/images/Test.png",
    eloRating: 1100,
    difficulty: "intermediate",
    category: "Winter Athletes",
    description:
      "Fast-paced player who loves racing down the board with quick attacks.",
    personality: "Downhill speed meets strategy!",
    playStyle: "aggressive",
    skillLevel: 6,
    depth: 7,
    thinkTimeMs: 1500,
    blunderChance: 0.12,
    aggressiveness: 40,
    openingBook: true,
    isActive: true,
    sortOrder: 22,
  },
  {
    name: "Curler",
    avatar: "🥌",
    avatarUrl: "/images/Test.png",
    eloRating: 1200,
    difficulty: "intermediate",
    category: "Winter Athletes",
    description:
      "Strategic and precise. Every move is calculated like a perfect throw.",
    personality:
      "Ready for a grueling game of intense and antagonistic competition?",
    playStyle: "defensive",
    skillLevel: 7,
    depth: 8,
    thinkTimeMs: 2500,
    blunderChance: 0.1,
    aggressiveness: -20,
    openingBook: true,
    isActive: true,
    sortOrder: 23,
  },
  {
    name: "Figure Skater",
    avatar: "⛸️",
    avatarUrl: "/images/Test.png",
    eloRating: 1300,
    difficulty: "intermediate",
    category: "Winter Athletes",
    description:
      "Elegant player who creates beautiful combinations with artistic flair.",
    personality: "Grace in every move",
    playStyle: "balanced",
    skillLevel: 8,
    depth: 9,
    thinkTimeMs: 2000,
    blunderChance: 0.08,
    aggressiveness: 0,
    openingBook: true,
    isActive: true,
    sortOrder: 24,
  },
  {
    name: "Hockey Player",
    avatar: "🏒",
    avatarUrl: "/images/Test.png",
    eloRating: 1400,
    difficulty: "intermediate",
    category: "Winter Athletes",
    description:
      "Aggressive and physical style. Will sacrifice material for the attack!",
    personality: "Aggressive and fast!",
    playStyle: "aggressive",
    skillLevel: 9,
    depth: 10,
    thinkTimeMs: 1500,
    blunderChance: 0.07,
    aggressiveness: 60,
    openingBook: true,
    isActive: true,
    sortOrder: 25,
  },

  {
    name: "Reze",
    avatar: "💣",
    avatarUrl: "/images/Test.png",
    eloRating: 1500,
    difficulty: "intermediate",
    category: "Anime",
    title: "FM",
    description:
      "Explosive and unpredictable. Will blow up your position when you least expect it.",
    personality: "Hi, can i be ur GF?",
    playStyle: "aggressive",
    skillLevel: 10,
    depth: 11,
    thinkTimeMs: 2000,
    blunderChance: 0.05,
    aggressiveness: 55,
    openingBook: true,
    isActive: true,
    sortOrder: 26,
  },
  {
    name: "Shikamaru",
    avatar: "🦌",
    avatarUrl: "/images/Test.png",
    eloRating: 1200,
    difficulty: "intermediate",
    category: "Anime",
    description:
      "Genius strategist who finds winning moves even when he seems bored.",
    personality: "What a drag...",
    playStyle: "defensive",
    skillLevel: 7,
    depth: 10,
    thinkTimeMs: 3500,
    blunderChance: 0.08,
    aggressiveness: -40,
    openingBook: true,
    isActive: true,
    sortOrder: 27,
  },
  {
    name: "Lelouch",
    avatar: "♟️",
    avatarUrl: "/images/Test.png",
    eloRating: 1700,
    difficulty: "advanced",
    category: "Anime",
    title: "CM",
    description:
      "Master tactician who always has a plan. Will outmaneuver you completely.",
    personality: "All according to plan",
    playStyle: "balanced",
    skillLevel: 12,
    depth: 14,
    thinkTimeMs: 2500,
    blunderChance: 0.03,
    aggressiveness: 20,
    openingBook: true,
    isActive: true,
    sortOrder: 28,
  },
  {
    name: "Light",
    avatar: "📓",
    avatarUrl: "/images/Test.png",
    eloRating: 1800,
    difficulty: "advanced",
    category: "Anime",
    title: "FM",
    description:
      "Calculating genius who plans many moves ahead. God complex included.",
    personality: "I'll take a potato chip... and eat it!",
    playStyle: "balanced",
    skillLevel: 13,
    depth: 15,
    thinkTimeMs: 2500,
    blunderChance: 0.02,
    aggressiveness: 30,
    openingBook: true,
    isActive: true,
    sortOrder: 29,
  },
  {
    name: "L Lawliet",
    avatar: "🍰",
    avatarUrl: "/images/Test.png",
    eloRating: 1900,
    difficulty: "advanced",
    category: "Anime",
    title: "FM",
    description:
      "World's greatest detective analyzes every position with extreme precision.",
    personality: "The probability is...",
    playStyle: "defensive",
    skillLevel: 14,
    depth: 16,
    thinkTimeMs: 4000,
    blunderChance: 0.015,
    aggressiveness: -30,
    openingBook: true,
    isActive: true,
    sortOrder: 30,
  },

  {
    name: "Cleopatra",
    avatar: "🐍",
    avatarUrl: "/images/Test.png",
    eloRating: 1800,
    difficulty: "advanced",
    category: "Historical",
    title: "FM",
    description: "Queen of strategy. Diplomatic yet deadly when cornered.",
    personality: "I will not be triumphed over",
    playStyle: "balanced",
    skillLevel: 13,
    depth: 14,
    thinkTimeMs: 2500,
    blunderChance: 0.025,
    aggressiveness: 15,
    openingBook: true,
    isActive: true,
    sortOrder: 31,
  },
  {
    name: "Einstein",
    avatar: "🧠",
    avatarUrl: "/images/Test.png",
    eloRating: 1900,
    difficulty: "advanced",
    category: "Historical",
    title: "FM",
    description:
      "Thinks outside the box. Creative solutions to complex positions.",
    personality: "Imagination is more important than knowledge",
    playStyle: "random",
    skillLevel: 14,
    depth: 15,
    thinkTimeMs: 3500,
    blunderChance: 0.02,
    aggressiveness: 5,
    openingBook: true,
    isActive: true,
    sortOrder: 32,
  },
  {
    name: "Napoleon",
    avatar: "🎖️",
    avatarUrl: "/images/Test.png",
    eloRating: 2000,
    difficulty: "advanced",
    category: "Historical",
    title: "FM",
    description:
      "Military genius who treats the chess board like a battlefield.",
    personality: "Victory belongs to the most persevering",
    playStyle: "aggressive",
    skillLevel: 15,
    depth: 16,
    thinkTimeMs: 2500,
    blunderChance: 0.015,
    aggressiveness: 50,
    openingBook: true,
    isActive: true,
    sortOrder: 33,
  },
  {
    name: "Da Vinci",
    avatar: "🎨",
    avatarUrl: "/images/Test.png",
    eloRating: 2100,
    difficulty: "master",
    category: "Historical",
    title: "IM",
    description:
      "Renaissance genius who sees patterns others miss. Elegant play.",
    personality: "Simplicity is the ultimate sophistication",
    playStyle: "balanced",
    skillLevel: 16,
    depth: 18,
    thinkTimeMs: 3000,
    blunderChance: 0.01,
    aggressiveness: 0,
    openingBook: true,
    isActive: true,
    sortOrder: 34,
  },
];

export async function seedBots() {
  try {
    const existingCount = await Bot.countDocuments();

    if (existingCount > 0) {
      console.log(`⏭️  Bots already seeded (${existingCount} bots exist)`);
      return { skipped: true, count: existingCount };
    }

    console.log("🤖 Seeding bots...");

    const result = await Bot.insertMany(botSeedData);

    console.log(`✅ Successfully seeded ${result.length} bots`);
    return { skipped: false, count: result.length };
  } catch (error) {
    console.error("❌ Error seeding bots:", error);
    throw error;
  }
}

export { botSeedData };
