import Puzzle from "../models/Puzzle.js";

const initialPuzzles = [
  {
    title: "Mate in 2",
    difficulty: "Easy",
    themes: ["Back Rank", "Queen Sac"],
    description: "Find the winning move for White.",
    icon: "🧩",
    fen: "6k1/5ppp/8/8/8/8/1Q3PPP/6K1 w - - 0 1",
    solution: ["Qb8+", "Qxf8#"],
    rating: 1100,
    isWhiteToMove: true,
  },
  {
    title: "Scholar's Mate",
    difficulty: "Easy",
    themes: ["Checkmate", "Quick Mate"],
    description: "White to move and checkmate.",
    icon: "🎓",
    fen: "r1bqkb1r/pppp1ppp/2n2n2/4p2Q/2B1P3/8/PPPP1PPP/RNB1K1NR w KQkq - 4 4",
    solution: ["Qxf7#"],
    rating: 800,
    isWhiteToMove: true,
  },
  {
    title: "Endgame Magic",
    difficulty: "Hard",
    themes: ["Promotion", "Opposition"],
    description: "White to move and promote.",
    icon: "♟️",
    fen: "8/8/8/8/8/4k3/4P3/4K3 w - - 0 1",
    solution: ["Kf1"],
    rating: 1600,
    isWhiteToMove: true,
  },
  {
    title: "Pin to Win",
    difficulty: "Medium",
    themes: ["Pin", "Skewer"],
    description: "Exploit the pinned piece.",
    icon: "📍",
    fen: "r2qkb1r/ppp2ppp/2n1bn2/4p3/4P3/1PN2N2/PBPP1PPP/R2QKB1R w KQkq - 0 6",
    solution: ["Bb5"],
    rating: 1350,
    isWhiteToMove: true,
  },
  {
    title: "Greek Gift",
    difficulty: "Hard",
    themes: ["Sacrifice", "King Hunt"],
    description: "Classic bishop sacrifice on h7.",
    icon: "🎁",
    fen: "r1bq1rk1/pppp1ppp/2n2n2/2b1p3/2B1P3/3P1N2/PPP2PPP/RNBQ1RK1 w - - 0 6",
    solution: ["Bxh7+"],
    rating: 1550,
    isWhiteToMove: true,
  },
  {
    title: "Smothered Mate",
    difficulty: "Hard",
    themes: ["Checkmate", "Knight"],
    description: "Beautiful mate with the knight.",
    icon: "⚔️",
    fen: "r1b1kb1r/pppp1Npp/5n2/8/3nq3/8/PPPPBPPP/RNBQK2R b KQkq - 0 1",
    solution: ["Qxe2#"],
    rating: 1500,
    isWhiteToMove: false,
  },
  {
    title: "Fork Attack",
    difficulty: "Easy",
    themes: ["Fork", "Knight"],
    description: "Win material with a knight fork.",
    icon: "🐴",
    fen: "r1bqkbnr/pppp1ppp/2n5/4p3/4P3/5N2/PPPP1PPP/RNBQKB1R w KQkq - 2 3",
    solution: ["Ng5"],
    rating: 1000,
    isWhiteToMove: true,
  },
  {
    title: "Anastasia's Mate",
    difficulty: "Hard",
    themes: ["Checkmate", "Sacrifice"],
    description: "Find the beautiful checkmate pattern.",
    icon: "👑",
    fen: "5rk1/1b3ppp/8/2RN4/8/8/5PPP/6K1 w - - 0 1",
    solution: ["Ne7+", "Kh8", "Rxh7#"],
    rating: 1700,
    isWhiteToMove: true,
  },
  {
    title: "Back Rank Mate",
    difficulty: "Medium",
    themes: ["Back Rank", "Checkmate"],
    description: "Exploit the weak back rank.",
    icon: "🏰",
    fen: "6k1/5ppp/8/8/8/8/5PPP/4R1K1 w - - 0 1",
    solution: ["Re8#"],
    rating: 1200,
    isWhiteToMove: true,
  },
  {
    title: "Discovered Attack",
    difficulty: "Medium",
    themes: ["Discovered Attack", "Tactics"],
    description: "Use a discovered attack to win material.",
    icon: "💡",
    fen: "r1bqkb1r/pppp1ppp/2n2n2/4p3/2B1P3/5N2/PPPP1PPP/RNBQK2R w KQkq - 4 4",
    solution: ["Ng5"],
    rating: 1300,
    isWhiteToMove: true,
  },
];

export async function seedPuzzles() {
  const count = await Puzzle.countDocuments();
  if (count > 0) return;

  await Puzzle.insertMany(initialPuzzles);
  console.log("✅ Puzzles seeded successfully");
}
