export interface AnalysisEntry {
  ply: number;
  cp?: number; 
  mate?: number; 
}

export interface GameHistory {
  _id: string;
  event: string;
  site: string;
  date: string; 
  round: string;
  white: string;
  black: string;
  result: string; 
  variant?: "standard" | "chess960";
  currentPosition: string;
  startingFen?: string;
  timeControl: string;
  utcDate: string;
  utcTime: string;
  startTime: string;
  endDate: string;
  endTime: string;
  whiteElo: number;
  blackElo: number;
  rated?: boolean;
  ratingBefore?: number;
  ratingAfter?: number;
  ratingDelta?: number;
  ratingDeviationBefore?: number;
  ratingDeviationAfter?: number;
  ratingDeviationDelta?: number;
  volatilityBefore?: number;
  volatilityAfter?: number;
  volatilityDelta?: number;
  isProvisional?: boolean;
  opponentRatingBefore?: number;
  opponentRatingAfter?: number;
  opponentRatingDelta?: number;
  opponentRatingDeviationBefore?: number;
  opponentRatingDeviationAfter?: number;
  opponentRatingDeviationDelta?: number;
  opponentVolatilityBefore?: number;
  opponentVolatilityAfter?: number;
  opponentVolatilityDelta?: number;
  opponentIsProvisional?: boolean;
  ratingPool?: "bullet" | "blitz" | "rapid" | "classical";
  eco: string;
  ecoUrl?: string;
  timezone?: string;
  link?: string;
  whiteUrl?: string;
  whiteCountry?: string;
  whiteTitle?: string;
  blackUrl?: string;
  blackCountry?: string;
  blackTitle?: string;
  moveText?: string;
  termination: string;
  moves: string[];
  pgn: string;
  playAs: "white" | "black";
  opponent: string;
  opponentLevel?: number;
  durationMs?: number;
  createdAt: string;
  analysis?: AnalysisEntry[];
  moveTimes?: number[]; 
}
